import Section1 from "@/components/about/section1"
import Footer from "@/components/Home/footer"
import Navbar from "@/components/Home/navbar"
import Head from "next/head"
import Image from "next/image"
import {motion} from 'framer-motion'

export default function Home() {
    return (
      <>
        <Head>
          <title>About | Cleaner Bubble</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>
      
            <motion.div 
             initial={{opacity:0,scale:1.3}}
             animate={{opacity:1,scale:1}}
             transition={{delay:0.6,duration:0.5}}
             viewport={{ once: true }}
            className="bg-img h-[60vh] -mt-24 md:h-[80vh] px-5 ">
                <div className="h-[30vh] md:h-[80vh] backdrop-blur-sm relative ">
            <motion.h3 
           
            className="text-center font-maison text-4xl md:text-5xl font-bold pt-52 md:pt-32 text-white pb-5 ">Tentang Kami</motion.h3>
            <motion.p 
             
            className="text-white text-xl font-maison  text-center">Ketahui perjalanan kami, dan orang-orang di belakangnya.</motion.p>
            <motion.div
            
            >
            <Image
          alt="Picture of the author"
          width={250}
          height={250} src="/asset/p1.png" className='absolute  left-1/2 -translate-x-1/2 w-[10rem] md:w-[15rem]'/></motion.div>
            </div>
            </motion.div>

          <div className="bg-gray-900">
            <div className="max-w-6xl mx-auto px-5 relative ">
             
                
                <h3 className="text-4xl text-white pt-24 md:text-5xl font-bold font-poppins">Perjalanan Cleaner Bubble</h3>

                <p className="py-12 text-xl text-white">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

                <p className="text-xl text-white">
                Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
                </p>
              <h3 className="pt-32 pb-12 text-white text-4xl md:text-5xl font-bold text-center">Nilai Yang Kami Pegang</h3>
                <Section1/>

               
            </div>
            </div>
            <Footer/>

        </>
  )
}
