import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Home/navbar'
import Image from 'next/image'
import Footer from '@/components/Home/footer'

function airmax() {
  return (
    <>
         <Head>
        <title>Blog | Airmax</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navbar/>
      <div className='max-w-3xl mx-auto pt-40 px-5'>
    <p className='text-xl  py-2 text-gray-500'>Bayu jaka | 25 januari 2023</p>
    <h3 className='text-3xl md:text-4xl font-bold font-poppins pb-12'>Desain unik Airmax 97</h3>
      <Image
                 alt="Picture of the author"
                 width={400}
                 height={400} src='/asset/airmax97.jpg' className='md:h-[24rem] h-[12rem]  w-[20rem] md:w-[40rem] object-cover rounded-md absolute left-1/2 -translate-x-1/2'/>

    <p className='md:mt-[27rem] mt-[14rem]  text-xl'>Sebuah sepatu Air Max 97 akan diluncurkan oleh Nike pada bulan September 2022. Sepatu ini diberi nama "M. Frank Rudy". Warnanya cerah, namun terkesan retro. Ternyata sepatu ini dibuat untuk memperingati hal yang paling penting dalam sejarah Nike. Sejarah tersebut melibatkan pendiri Nike Phil Knight, dan insinyur NASA Marion Frank Rudy. 

Sebelum juah tentang cerita sepatunya, alangkah baiknya kita tahu dulu bagaimana sejarah kedua orang tersebut. Philip Hampson Knight atau Phil Knight adalah pengusaha Amerika Serikat yang menjadi salah satu pendiri Nike, Inc.. Knight memulai perjalanan keliling dunia setelah lulus kuliah, hingga pada November 1962 dia menemukan sepatu lari merek Tiger. Sepatu tersebut diproduksi di Kobe, Jepang oleh perusahaan bernama Onitsuka Co.. Perusahaan tersebut sekarang dikenal sebagai Asics. </p>

<p className='text-xl py-5'>
Dengan otak bisnisnya, Knight meminta izin untuk menjual Tiger ke Amerika. Namun saat kembali ke Amerika, Knight terkejut karena rekannya, Bowerman, tidak hanya memesan sepatu Tiger untuk dipakai atau dijual. Bowerman malah menjadikan sepatu tersebut ide untuk desain produk. Akhirnya Knight dan Bowerman mendirikan perusahaan Blue Ribbon Sports yang menjadi cikal bakal Nike pada 25 Januari 1964. Dari sinilah sejarah sepatu olahraga Nike dimulai. 

Sementara itu, Marion Frank Rudy adalah seorang aeronautical engineer yang bekerja untuk NASA. Frank Rudy menerima hak paten atas sistem bantalan gas inert yang dikemas dalam plastik poliuretan. Pada tahun 1978, Frank Rudy bertemu dengan Phil Knight. Dia memberikan ide terobosan baru di dunia sepatu. Idenya adalah memasukkan bantalan udara yang dibuatnya ke midsole sneakers. Teknologi tersebut yang akhirnya dipatenkan dengan nama "Nike Air" pada tahun 1980. 
</p>

<p className='text-xl pb-12'>Air Max 97 merupakan sebuah karya Phil Knight yang memakai teknologi miliki Frank Rudy. Untuk merayakan sejarah tersebut, Nike membuat sepatu Air Max 97 "M. Frank Rudy". Sepatu tersebut memakai dasar kanvas "Summit White", dengan kombinasi abu-abu muda dengan bahan suede di bagian mudguard. Sebagai ornamen ada warna oranye, kuning, dan biru. Logo Swoosh ditampilkan seperti coretan. Sedangkan di midsole bagian tengah tercetak tulisan "Est. 1997". 

Untuk midsole, jelas sepatu ini menggunakan sistem Nike Air. Sedangkan untuk outsole dipakai karet warna kuning agar selaras dengan bagian atas. Sebagai pelengkap, Nike memberikan hangtag sebuah pengukur tekanan udara. Sepatu ini akan dilepas ke pasaran dengan harga AS$185 atau setara dengan 2,7 juta rupiah. (*)</p>
    
      </div>

      <Footer/>
    </>
  )
}

export default airmax