import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import Navbar from '@/components/Home/navbar'
import Footer from '@/components/Home/footer'
import Link from 'next/link'

function Blog() {
  return (
    <>
         <Head>
        <title>Blog | Cleaner Bubble</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Navbar/>
<div className='bg-gray-900 -mt-24 pt-24' >

    <div className='max-w-6xl mx-auto pt-24 px-5'>
        <h3 className='text-4xl font-bold text-white'>Berita Terbaru</h3>
        <p className='text-gray-100 text-xl pb-20'>Temukan berita seputar sepatu dan lain-lain terbaru yang dapat menambah wawasan kita</p>
           <div className='flex flex-wrap justify-center  pb-24 md:space-x-12 lg:space-x-24 '>
                <div className='w-full md:w-3/12 relative pb-20'>
                    <Image
                 alt="Picture of the author"
                 width={350}
                 height={350} src='/asset/adidasg.webp' className='h-[10rem] w-[18rem] object-cover rounded-md absolute left-1/2 -translate-x-1/2'/>
                    <h3 className=' mt-44 mx-9 md:mx-0  pb-2 font-semibold text-2xl font-poppins text-white'>Cerita dibalik sepatu Jordan</h3>
                    <p className='text-gray-300 mx-9 md:mx-0 '>Informasi/ 23 januari 2023</p>
                    
                  
                </div>
                <div className='w-full md:w-3/12 relative pb-20'>
                    <Image
                 alt="Picture of the author"
                 width={350}
                 height={350} src='/asset/casual.jpg' className='h-[10rem] w-[18rem] object-cover rounded-md absolute left-1/2 -translate-x-1/2'/>
                    <h3 className=' mt-44 mx-9 md:mx-0 pb-2 font-semibold text-2xl font-poppins text-white'>Adidas Spezial identik dengan suporter</h3>
                    <p className=' text-gray-300 mx-9 md:mx-0'>Informasi/ 23 januari 2023</p>
                </div>
                <div className='w-full md:w-3/12 relative pb-20'>
                    <Image
                 alt="Picture of the author"
                 width={350}
                 height={350} src='/asset/airmax97.webp' className='h-[10rem] w-[18rem] object-cover rounded-md absolute left-1/2 -translate-x-1/2'/>
                    <h3 className=' mt-44 mx-9 md:mx-0 pb-2 font-semibold text-2xl font-poppins text-white'>Asal usul bentuk dari airmax-97</h3>
                    <p className=' text-gray-300 mx-9 md:mx-0'>Informasi/ 23 januari 2023</p>
                    
                </div>
               
               
            </div>
    </div>
    </div>
    <Footer/>
    </>  
  )
}

export default Blog