import Footer from "@/components/Home/footer"
import Navbar from "@/components/Home/navbar"
import Clean from "@/components/servis/clean"
import Other from "@/components/servis/other"
import Repaint from "@/components/servis/repaint"
import Head from "next/head"


export default function Services() {
    return (
      <>
        <Head>
          <title>Services | Cleaner Bubble</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

      <Navbar/>
   
            
          <div className="bg-gray-900 -mt-24 py-24">
          <Clean/>
       

          </div>

          <Footer/>


        </>
  )
}
